OBSERVATION_SIZE = 14
ACTION_SIZE = 3
ENEMY_OBSERVATION_SLOTS = 3

SELF_X_INDEX = 0
SELF_Z_INDEX = 1
SELF_YAW_INDEX = 2
TARGET_X_INDEX = 3
TARGET_Z_INDEX = 4

OBSERVATION_HEADER_SIZE = 5
ENEMY_FEATURE_SIZE = 3
